### ISSUE TITLE
'module' object has no attribute 'TOKEN_VAR'

### ISSUE THREAD

**Issue by Mark-Shine** [bitmazk/django-user-media#7]
it seems related to "verbatim" tag

django version is 1.9.1

When I 

> use {% include "user_media/partials/image_upload.html" with object=request.user.get_profile field='logo' mode="single" show_main_thumb="True" %}

**Comment by Tyrdall** [comment]
@Mark-Shine Please install ``django-libs==1.66.13`` and try again

**Comment by Mark-Shine** [comment]
@Tyrdall  yeah I have upgrade to 1.66.13 but still get this error

**Comment by Tyrdall** [comment]
@Mark-Shine Can you send me the output of ``pip freeze``?
