### ISSUE TITLE
The CSS file 'user_media/css/libs/jquery.fileupload-ui.css' references a file which could not be found

### ISSUE THREAD

**Issue by emmurd** [bitmazk/django-user-media#8]
This error occured while collecting the static file for my project. `./manage.py collectstatic`

`The CSS file 'user_media/css/libs/jquery.fileupload-ui.css' references a file which could not be found:
  user_media/css/img/progressbar.gif
`

I looked in the code and in fact, there's no _progressbar.gif_ in the img folder. There's others references too that dosen't exist in the project path.

**Comment by emmurd** [comment]
The problem come from WhiteNoise. Sorry to bother.

**Comment by dhcrain** [comment]
Curious how you fixed this, I am having the same issue.

**Comment by emmurd** [comment]
If you are using WhiteNoise to manage your static files, it requires that all files are inside the project. You can't have a google font for example. So I had no choice to not using WhiteNoise and use the default static manager.

**Comment by dhcrain** [comment]
I am using WhiteNoise and got the exact same error you got when it was looking for the progressbar.gif. 

So you went back to the default static manager? sadly not a choice for me....
Thank you.
